### ISSUE TITLE
Build project roadmap and milestones

### ISSUE THREAD

**Issue by rlwhall** [rlwhall/CLASSIC_DRI_Tutorial#2]
Todo:
- [x] Write roadmap description
- [x] Create 3 milestones
- [x] Create tasks to accomplish milestones
- [x] Share roadmap on OLS issue
